user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile    off;
    access_log  off;
    keepalive_timeout  120;
    gzip  on;

    upstream web_server {
         server 192.168.133.10:33382;
    }

    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /etc/nginx/html;
            index  index.html index.htm;
        }

        location /WebMineManage/ {
            root   /etc/nginx/html/;
            try_files $uri $uri/ /WebMineManage/index.html;
        }

        location /net/ {
            proxy_pass  http://web_server;
        }

        location /DigitizingMine/ {
            proxy_pass  http://web_server;
        }

        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
